article: https://www.hackster.io/jakub-smejkal/hardwario-iot-kit-lcd-monitor-of-netio-sockets-b5b1fa
video: https://www.youtube.com/watch?v=5fihG2xp4y8
articles:
  - title: HARDWARIO LCD monitor of NETIO sockets
    url: https://www.hackster.io/jakub-smejkal/hardwario-iot-kit-lcd-monitor-of-netio-sockets-b5b1fa
    description: You can control and monitor up to 3 devices connected to the NETIO smart socket with just BigClown LCD Kit.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050344/_GIEKcC4VbB.blob?auto=compress%2Cformat&w=900&h=675&fit=min
images:
  - title:
    url: https://github.com/hardwario/website/blob/master/static/kits-images/lcd-thermostat/main.png
assembly:
  - name: HARDWARIO LCD Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
